Repository theplant/appkit, pull requests merged in 2022-12, with the labels that each got.

#73 upgrade airbrake to v5.6.0
  errornotifier/airbraker.go
  go.mod
  go.sum
Labels: size/L

#74 Upgrade gobrake to fix vulnerabilities
  go.mod
  go.sum
Labels: size/XXL

#75 github-actions: updated checkout and codeql
  .github/workflows/codeql-analysis.yml
Labels: size/XS
